### ISSUE TITLE
Segger source code 

### ISSUE THREAD

**Issue by RodenLuo** [nanovis/DiffFit#43]
Hi Tom @tomgoddard,

I couldn't find Segger's source code in the ChimeraX GitHub repo. I did notice `seggerx_2024_08_12.tar.gz` from https://github.com/RBVI/ChimeraX/blob/develop/src/bundles/segger/Makefile. I also found https://github.com/tomgoddard/segger/tree/master. May I safely assume the repo in your account has and will have the latest source code for Segger's ChimeraX bundle? Thanks.

**Comment by tomgoddard** [comment]
Hi Roden,

Yes my fork of the Segger source code https://github.com/tomgoddard/segger/tree/master is what is in ChimeraX.   We don't include third-party packages directly in the ChimeraX github repository, instead they are fetched from PyPi if on PyPi or from our lab server.  The Makefile you found fetches a Segger tarball using

    curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/segger/seggerx_2024_08_12.tar.gz

Greg Pintilie @gregdp wrote Segger for Chimera and I did this initial port to ChimeraX.  I've been trying to get Greg to move to ChimeraX ever since.  He still develops Segger for Chimera -- I see his repository is 72 commits ahead of my fork and mine is 73 commits ahead of his (the porting changes plus later bug fixes).
